# Generated by Django 6.0.4 on 2026-04-24 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.FloatField()),
                ('current_lat', models.FloatField(null=True)),
                ('current_lng', models.FloatField(null=True)),
                ('pickup_lat', models.FloatField(null=True)),
                ('pickup_lng', models.FloatField(null=True)),
                ('dropoff_lat', models.FloatField(null=True)),
                ('dropoff_lng', models.FloatField(null=True)),
                ('total_distance_miles', models.FloatField(null=True)),
                ('total_duration_hours', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(choices=[('driving', 'Driving'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('rest_30min', 'Rest 30min'), ('rest_10hr', 'Rest 10hr'), ('fuel', 'Fuel')], max_length=255)),
                ('location_name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('duration_hours', models.FloatField()),
                ('order', models.IntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ELDLogSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('date', models.DateField()),
                ('log_data', models.JSONField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sheets', to='trips.trip')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
    ]
